config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  username == 'admin' && password == 'qwerty'
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/async/tasks'
  mount ActionCable.server => '/app-cable'

  root to: "notes#index"

  devise_for :users
  resources  :notes

  get '/search' => 'search#search', as: :search
end

# For details on the DSL available within this file,
# see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  validates :title,   presence: true
  validates :content, presence: true

  scope :random, ->{ order('RANDOM()') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note
      .order('created_at DESC')
      .page(params[:page])
      .per(params[:per_page])
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :content)
    end
end

app/controllers/protozaur_controller.rb
class ProtozaurController < ApplicationController
  layout '../protozaur/layout/base'

  def index
    define_view(:floating)
  end

  def flex
    define_view(:holder)
  end

  def framework
    define_view(:font_family)
  end

  def inputs_buttons
    define_view(:inputs)
  end

  private

  def define_view(default_view)
    @view = params[:view] ? params[:view] : default_view
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @q = params[:q].to_s.strip
    to_search = ::Riddle::Query.escape @q

    @notes = ::ThinkingSphinx.search(
      to_search,
      star: true,
      classes: [ Note ],
      field_weights: {
        title: 5,
        content: 3
      },
      per_page: 24
    )
    .page(params[:page])
    .per(params[:per_page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channel_helper.rb
# http://stackoverflow.com/questions/39103685/can-you-invoke-jbuilder-to-create-a-native-rails-object-instead-of-a-rendered-st
module ChannelHelper
  def broadcast(channel, message)
    ActionCable.server.broadcast(channel, message)
  end

  def render_view(args)
    ApplicationController.render(args)
  end

  def render_json(args)
    JSON.parse render_view(args)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/analytics/index.slim
= link_to 'Our Story', '#', class: :about_info
= link_to 'User Voice', '#', class: :about_info

ul.main_menu-holder
  li.main_menu-item = link_to 'About', '#', class: 'main_menu-item_link'
  li.main_menu-item = link_to 'Articles', '#', class: 'main_menu-item_link'
  li.main_menu-item = link_to 'Videos', '#', class: 'main_menu-item_link'
  li.main_menu-item = link_to 'Open Source', '#', class: 'main_menu-item_link'
  li.main_menu-item = link_to 'Contacts', '#', class: 'main_menu-item_link'

ul.video_list-holder
  li.video_list-item = link_to 'Getting Started', '#', class: 'video_list-item_link'
  li.video_list-item = link_to 'Basics. Episode 1', '#', class: 'video_list-item_link'
  li.video_list-item = link_to 'Basics. Episode 2', '#', class: 'video_list-item_link'
  li.video_list-item = link_to 'How to contribute', '#', class: 'video_list-item_link'
  li.video_list-item = link_to 'License', '#', class: 'video_list-item_link'

ul.main_menu-holder
  li.main_menu-item
    = link_to 'About', '#', class: 'main_menu-item_link'
    = link_to 'Our Story', '#', class: :about_info
    = link_to 'User Voice', '#', class: :about_info

  li.main_menu-item = link_to 'Articles', '#', class: 'main_menu-item_link'
  li.main_menu-item
    .main_menu-item_link Videos

    ul.video_list-holder
      li.video_list-item = link_to 'Getting Started', '#', class: 'video_list-item_link'
      li.video_list-item = link_to 'Basics. Episode 1', '#', class: 'video_list-item_link'
      li.video_list-item = link_to 'Basics. Episode 2', '#', class: 'video_list-item_link'
      li.video_list-item = link_to 'How to contribute', '#', class: 'video_list-item_link'
      li.video_list-item = link_to 'License', '#', class: 'video_list-item_link'

  li.main_menu-item = link_to 'Open Source', '#', class: 'main_menu-item_link'
  li.main_menu-item = link_to 'Contacts', '#', class: 'main_menu-item_link'

app/views/layouts/application.html.slim
doctype html

html.w100p.h100p
  head
    meta charset='utf-8'
    title Rails5App

    = action_cable_meta_tag
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.w100p.h100p.ffa
    .w80p.ma
      .mt20.mb20
        = yield

app/views/notes/_form.html.slim
- if @note.errors.any?
  #error_explanation.mb40
    .fs22.mb20 = "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
    ul.ul
      - @note.errors.full_messages.each do |message|
        li.li.fs18.lh130 = message

= form_for @note do |f|
  .field.mb20
    = f.label :title, class: 'block mb10 fs16'
    = f.text_field :title, class: 'ptz_input ptz_size-16 w400'
  .field.mb20
    = f.label :content, class: 'block mb10 fs16'
    = f.text_area :content, class: 'ptz_textarea ptz_size-16 w400', rows: 7
  .actions
    = f.submit 'Save Note', class: 'ptz_btn ptz_size-18'

app/views/notes/edit.html.slim
.fs24.mb50 Editing note

.mb50== render 'form'

= link_to 'Show', @note, class: 'ptz_btn ptz_size-14 mr30'
= link_to 'Back to Index page', notes_path, class: 'ptz_btn ptz_size-14'

app/views/notes/index.html.slim
.ptz_table.fs24.mb50
  .ptz_td.vam
    | Notes Index
  .ptz_td.vam.pl30
    = link_to 'Create New Note', new_note_path, class: 'ptz_btn ptz_size-18'

- if @notes.blank?
  .fs20.mb20 There is no any note yet
- else
  .pull-right.w300.ml20.mb20
    .mb30= render partial: 'search/form'
    .mb10= render(template: 'notes/random', locals: { note: Note.random.first })
    .mb20.fs14.i.js-current-time= Time.now.to_s(:db)

  = render template: 'notes/list', locals: { notes: @notes }
  .fs18.lh120
    = paginate @notes

app/views/notes/list.html.slim
- notes.each do |note|
  .mb30
    .fs18.lh130.mb10.b= link_to note.title, note
    .fs16.lh130.mb10= note.content
    .fs16
      span.mr30
        | by:
        - if note.user
          span.i<= note.user.email
        - else
          span.i Guest

      span.mr30
        | created at:
        span.i<= note.created_at.to_s(:db)

app/views/notes/new.html.slim
.fs24.mb50 New note

.mb50== render 'form'

= link_to 'Back to Index page', notes_path, class: 'ptz_btn ptz_size-14'

app/views/notes/random.html.slim
.p20.notes-random.js-notes-random_note
  .fs18.b.mb10.lh130= note.title
  .fs15.lh130= note.content

app/views/notes/show.html.slim
- if notice.present?
  .fs18.mb30#notice
    = notice

.fs24.lh130.mb40= @note.title
.fs18.lh130.mb40= @note.content

= link_to 'Edit', edit_note_path(@note), class: 'ptz_btn ptz_size-14 mr30'
= link_to 'Back to Index page', notes_path, class: 'ptz_btn ptz_size-14'

app/views/protozaur/flex.html.slim
.w100p
  .ptz_btn-group.mb20
    = render template: "protozaur/header"

.ptz_table.w100p
  .ptz_td

    ruby:
      links = {
        'Holder'      => 'holder',
        'Direction'   => 'direction',
        'Justify'     => 'justify',
        'Wrap'        => 'wrap',
        'Flow'        => 'flow',
        'Align items' => 'align_items',
        'Align content' => 'align_content',
        'Align self'  => 'align_self'
      }

    - links.each_pair do |k, v|
      - current = 'current' if v.to_s == @view.to_s
      .mb20= link_to k, ptz_flex_path(view: v), class: "ptz_btn ptz_size-18 #{current}"

  .ptz_td.pl40.w100p
    = render template: "protozaur/views/flex/#{@view}"

app/views/protozaur/framework.html.slim
.w100p
  .ptz_btn-group.mb20
    = render template: "protozaur/header"

.ptz_table.w100p
  .ptz_td

    ruby:
      links = {
        'Font family' => 'font_family',
        'Line height' => 'line_height',
        'Font size'   => 'font_size',
        'Block model' => 'block_model',
        'Padding'     => 'paddings',
        'Margins'     => 'margins',
        'Textareas'   => 'textareas',
        'Width'       => 'width'
      }

    - links.each_pair do |k, v|
      - current = 'current' if v.to_s == @view.to_s
      .mb20= link_to k, ptz_framework_path(view: v), class: "ptz_btn ptz_size-18 #{current}"

  .ptz_td.pl40.w100p
    = render template: "protozaur/views/framework/#{@view}"

app/views/protozaur/header.html.slim
- current = current_page?(controller: :protozaur, action: :index) ? :current : nil
= link_to 'Index / Base', root_path, class: "ptz_btn ptz_size-18 #{current}"

- current = current_page?(controller: :protozaur, action: :framework) ? :current : nil
= link_to 'Framework', ptz_framework_path, class: "ptz_btn ptz_size-18 #{current}"

- current = current_page?(controller: :protozaur, action: :inputs_buttons) ? :current : nil
= link_to 'Inputs / Buttons', ptz_inputs_buttons_path, class: "ptz_btn ptz_size-18 #{current}"

- current = current_page?(controller: :protozaur, action: :flex) ? :current : nil
= link_to 'Flex', ptz_flex_path, class: "ptz_btn ptz_size-18 #{current}"

app/views/protozaur/index.html.slim
.w100p
  .ptz_btn-group.mb20
    = render template: "protozaur/header"

.ptz_table.w100p
  .ptz_td

    ruby:
      links = {
        'floating'    => 'floating',
        'headers'     => 'headers',
        'links'       => 'links',
        'lists'       => 'lists',
        'paragraph'   => 'paragraph',
        'Sup / Sub'   => 'sup_sub',
        'Visibility'  => 'visibility',
        'Other'       => 'other'
      }

    - links.each_pair do |k, v|
      - current = 'current' if v.to_s == @view.to_s
      .mb20= link_to k, root_path(view: v), class: "ptz_btn ptz_size-18 #{current}"

  .ptz_td.pl40.w100p
    = render template: "protozaur/views/base/#{@view}"

app/views/protozaur/inputs_buttons.html.slim
.w100p
  .ptz_btn-group.mb20
    = render template: "protozaur/header"

.ptz_table.w100p
  .ptz_td

    ruby:
      links = {
        'Inputs'      => 'inputs',
        'Buttons'     => 'buttons',
        'Checkboxes'  => 'checkboxes',
        'Radio buttons' => 'radiobuttons',
        'File input' => 'fileinputs'
      }

    - links.each_pair do |k, v|
      - current = 'current' if v.to_s == @view.to_s
      .mb20= link_to k, ptz_inputs_buttons_path(view: v), class: "ptz_btn ptz_size-18 #{current}"

  .ptz_td.pl40.w100p
    = render template: "protozaur/views/inputs_buttons/#{@view}"

app/views/protozaur/layout/base.html.slim
doctype html

html.w100p.h100p
  head
    title Protozaur CSS Framework
    = action_cable_meta_tag
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body.w100p.h100p.ffa
    = render template: 'protozaur/layout/body'

app/views/protozaur/layout/body.html.slim
.w80p.ma.mt20.mb20
  = yield

app/views/protozaur/views/base/floating.html.slim
.fs25.mb50 Floating

.mb50.clearfix
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      div
        .pull-left Hello
        .pull-left World

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div>
        <div class='pull-left'>Hello</div>
        <div class='pull-left'>World</div>
      </div>

  div.showme.fs18
    .pull-left.showme.p15 Hello
    .pull-left.showme.p15 World

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .clearfix
        .pull-left Hello
        .pull-left World

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='clearfix'>
        <div class='pull-left'>Hello</div>
        <div class='pull-left'>World</div>
      </div>

  .clearfix.showme.fs18
    .pull-left.showme.p15 Hello
    .pull-left.showme.p15 World

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .clearfix
        .pull-left Hello
        .pull-right World

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='clearfix'>
        <div class='pull-left'>Hello</div>
        <div class='pull-right'>World</div>
      </div>

  .clearfix.showme.fs18
    .pull-left.showme.p15 Hello
    .pull-right.showme.p15 World


.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .ofh.br-off.w100(style='height:50px')
        | All work and no play makes Jack a dull boy!
        | All work and no play makes Jack a dull boy!

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='ofh w100 br-off' style='height:50px'>
        All work and no play makes Jack a dull boy!
        All work and no play makes Jack a dull boy!
      </div>

  .ofh.lh120.fs18.w100.showme.br-off(style='height:50px')
    | All work and no play makes Jack a dull boy!
    | All work and no play makes Jack a dull boy!


.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .ofh.br-off.w100.xscroll(style='height:50px')
        | All work and no play makes Jack a dull boy!
        | All work and no play makes Jack a dull boy!

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='ofh w100 br-off xscroll' style='height:50px'>
        All work and no play makes Jack a dull boy!
        All work and no play makes Jack a dull boy!
      </div>

  .ofh.lh120.fs18.w100.showme.br-off.xscroll(style='height:50px')
    | All work and no play makes Jack a dull boy!
    | All work and no play makes Jack a dull boy!

div
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .ofh.br-off.w100.yscroll(style='height:50px')
        | All work and no play makes Jack a dull boy!
        br
        | All work and no play makes Jack a dull boy!
        br
        | All work and no play makes Jack a dull boy!
        br
        | All work and no play makes Jack a dull boy!

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='ofh w100 br-off yscroll' style='height:50px'>
        All work and no play makes Jack a dull boy!
        <br>
        All work and no play makes Jack a dull boy!
        <br>
        All work and no play makes Jack a dull boy!
        <br>
        All work and no play makes Jack a dull boy!
      </div>

  .ofh.lh120.fs18.w100.showme.br-off.yscroll(style='height:50px')
    | All work and no play makes Jack a dull boy!
    br
    | All work and no play makes Jack a dull boy!
    br
    | All work and no play makes Jack a dull boy!
    br
    | All work and no play makes Jack a dull boy!

app/views/protozaur/views/base/headers.html.slim
.fs25.mb50 Headers

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      h1 Header 1
      h2 Header 2
      h3 Header 3
      h4 Header 4
      h5 Header 5
      h6 Header 6

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <h1>Header 1</h1>
      <h2>Header 2</h2>
      <h3>Header 3</h3>
      <h4>Header 4</h4>
      <h5>Header 5</h5>
      <h6>Header 6</h6>

  .showme.p15
    h1 Header 1
    h2 Header 2
    h3 Header 3
    h4 Header 4
    h5 Header 5
    h6 Header 6

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      h1.fs30 Header 1
      h2.fs20 Header 2
      h3.fs10 Header 3
      h4.fs10 Header 4
      h5.fs20 Header 5
      h6.fs30 Header 6

  .showme.fs18.p15
    h1.fs30 Header 1
    h2.fs20 Header 2
    h3.fs10 Header 3
    h4.fs10 Header 4
    h5.fs20 Header 5
    h6.fs30 Header 6

app/views/protozaur/views/base/index.html.slim
= image_tag 'https://raw.githubusercontent.com/the-teacher/protozaur/master/docs/logo_550x550.jpg', class: 'app-img_rounded_corners_1'

app/views/protozaur/views/base/links.html.slim
.fs25.mb50 Links

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      a href='#' This is a Link

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <a href='#'>This is a Link</a>

  .p20.showme
    a.fs15 href='#' This is a Link

app/views/protozaur/views/base/lists.html.slim
.fs25.mb50 Lists

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      ol
        li List Item
        li List Item
        li List Item
        li List Item

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <ol>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
      </ol>

  .p20.showme
    ol.fs18.lh120
      li List Item
      li List Item
      li List Item
      li List Item

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      ol.ol
        li List Item
        li List Item
        li List Item
        li List Item

      ol.ul
        li List Item
        li List Item
        li List Item
        li List Item

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <ol class='ol'>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
      </ol>

      <ol class='ul'>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
        <li>List Item</li>
      </ol>

  .p20.showme
    ol.ol.fs18.lh120
      li List Item
      li List Item
      li List Item
      li List Item

    ol.ul.fs18.lh120
      li List Item
      li List Item
      li List Item
      li List Item

app/views/protozaur/views/base/other.html.slim
.fs25.mb50 Other

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .text_select-off
        | You can not select this text

      .text_select-on
        | You can select this text

      hr

      noscript
        | There is no JavaScript

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <div class='text_select-off'>
        You can not select this text
      </div>

      <div class='text_select-on'>
        You can select this text
      </div>

      <hr>

      <noscript>
        There is no JavaScript
      </noscript>

  .showme.p10.fs16
    .text_select-off.p10.mb20
      | You can not select this text

    .text_select-on.p10
      | You can select this text

    hr

    noscript
      | There is no JavaScript

app/views/protozaur/views/base/paragraph.html.slim
.fs25.mb50 Paragraph

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      p= "All work and no play makes Jack a dull boy! " * 20

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      <p>
        All work and no play makes Jack a dull boy!
        ...
        All work and no play makes Jack a dull boy!
      </p>

  .showme
    p= "All work and no play makes Jack a dull boy! " * 20

app/views/protozaur/views/base/sup_sub.html.slim
.fs25.mb50 Sup / Sub

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      All <sup>work</sup> and no play makes <sub>Jack</sub> a dull boy!

  xmp.showme.p10.mb20.fs18.lh130
    erb:
      All <sup>work</sup> and no play makes <sub>Jack</sub> a dull boy!


  .showme.p10.fs16
    | All <sup>work</sup> and no play makes <sub>Jack</sub> a dull boy!

app/views/protozaur/views/base/visibility.html.slim
.fs25.mb50 Visibility

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .hidden
        This is hidden block

      .invisible
        This is invisible block

      .visible
        This is visible block

      .solid-0
        This is solid block 0

      .solid-1
        This is solid block 1

  .showme.p10.fs16
    .hidden This is hidden block

    .invisible This is invisible block

    .visible.mb20.p10 This is invisible block

    .solid-0.mb20.p10 This is solid block 0

    .solid-1.p10 This is solid block 1

app/views/protozaur/views/flex/align_content.html.slim
.fs25.mb50 Align Content

- %w[ st s e c b a ].each do |klass|
  - klass = "flex-ac_#{klass}"

  .mb50
    xmp.showme.p10.mb20.fs18.lh130
      erb:
        .flex-holder.flex-flow_row_wrap.<%= klass %>(style='height:300px')
          div Item 1
          div Item 2
          ...
          div Item 20

    .showme.fs18
      .flex-holder.ofh.w600.flex-flow_row_wrap(style='height:300px' class=klass)
        - 20.times do |i|
          div.showme.p15 Item&nbsp;#{ i.next }

app/views/protozaur/views/flex/align_items.html.slim
.fs25.mb50 Align Items

- %w[ st c b s e ].each do |klass|
  - klass = "flex-ai_#{klass}"

  .mb50
    xmp.showme.p10.mb20.fs18.lh130
      erb:
        .flex-holder.<%= klass %>(style='height:100px')
          div Item 1
          div Item 2
          ...
          div Item 20

    .showme.fs18
      .flex-holder.ofh.w600(style='height:100px' class=klass)
        - 20.times do |i|
          div.showme.p15 Item&nbsp;#{ i.next }

app/views/protozaur/views/flex/align_self.html.slim
.fs25.mb50 Align self

.mb50
  xmp.showme.p10.mb20.fs18.lh130
    erb:
      .flex-holder(style='height:300px')
        div.flex-item_as_a Item A
        div.flex-item_as_b Item B
        div.flex-item_as_s Item S
        div.flex-item_as_c Item C
        div.flex-item_as_e Item E
        div.flex-item_as_st Item St

  .showme.fs18
    .flex-holder(style='height:300px')
      div.showme.p15.flex-item_as_a Item A
      div.showme.p15.flex-item_as_b Item B
      div.showme.p15.flex-item_as_s Item S
      div.showme.p15.flex-item_as_c Item C
      div.showme.p15.flex-item_as_e Item E
      div.showme.p15.flex-item_as_st Item St

app/views/protozaur/views/flex/direction.html.slim
.fs25.mb50 Flex direction

- %w[ dir_row dir_rrow dir_col dir_rcol ].each do |klass|
  .mb50
    xmp.showme.p10.mb20.fs18.lh130
      erb:
        .flex-holder.flex-<%= klass %>(style='height:100px')
          div Item 1
          div Item 2
          ...
          div Item 20

    .showme.fs18
      .flex-holder.ofh.w600(style='height:100px' class="flex-#{klass}")
        - 20.times do |i|
          div.showme.p15 Item&nbsp;#{ i.next }

app/views/protozaur/views/flex/flow.html.slim
.fs25.mb50 Flex flow

- %w[ row rrow col rcol ].each do |dir|
  - %w[ nowrap wrap rwrap ].each do |wrap|
    - klass = "flex-flow_#{dir}_#{wrap}"
    .mb50
      xmp.showme.p10.mb20.fs18.lh130
        erb:
          .flex-holder.<%= klass %>(style='height:100px')
            div Item 1
            div Item 2
            ...
            div Item 20

      .showme.fs18
        .flex-holder.ofh.w600(style='height:100px' class=klass)
          - 20.times do |i|
            div.showme.p15 Item&nbsp;#{ i.next }

app/views/protozaur/views/flex/index.html.slim
= image_tag 'https://raw.githubusercontent.com/the-teacher/protozaur/master/docs/logo_550x550.jpg', class: 'app-img_rounded_corners_1'

app/views/search/_form.html.slim
= form_tag search_path, method: :get, enforce_utf8: false, class: 'search-form p20' do
  .mb20= text_field_tag :q, params[:q], placeholder: 'Search query', class: 'ptz_input ptz_size-18 w100p'
  = submit_tag 'Search', class: 'js-search-submit_btn ptz_btn ptz_size-18', autocomplete: false

app/views/search/search.html.slim
.mb30= link_to 'Back to Index page', notes_path, class: 'ptz_btn ptz_size-14'

.fs24.mb25
  | Search by:
  =< @q

- if @notes.count > 0
  .mb50.fs15.i
    | Results:
    =<> @notes.size
    | of
    =< @notes.count

.mb25= render partial: 'search/form'

- if @notes.blank?
  .fs20.mb20 Nothing to show
- else
  = render template: 'notes/list', locals: { notes: @notes }
  .fs18.lh120
    = paginate @notes